### ISSUE TITLE
Method Channel does not exist

### ISSUE THREAD

**Issue by matthewrice345** [g123k/flutter_is_emulator#1]
When using the plugin it seems to not work. 

```
MissingPluginException(No implementation found for method isEmulatorOrSimulator on channel g123k/flutter_is_emulator)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      FlutterIsEmulator.isDeviceAnEmulatorOrASimulator (package:flutter_is_emulator/flutter_is_emulator.dart:11:24)
    <asynchronous suspension>
```

I'm testing on an Android Pixel C tablet emulator. 

Calling `await FlutterIsEmulator.isDeviceAnEmulatorOrASimulator` in an async function.

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
> [✓] Android Studio (version 3.1)
> [✓] IntelliJ IDEA Community Edition (version 2017.3.4)
> [!] VS Code (version 1.27.1)
> [✓] Connected devices (1 available)

**Comment by dirablue** [comment]
> Exception has occurred.
> MissingPluginException (MissingPluginException(No implementation found for method
> isEmulatorOrSimulator on channel g123k/flutter_is_emulator))

I faced the same error on Android Emulator

**Comment by g123k** [comment]
Hello,

Have you tried to clean your project and launch your app again?

**Comment by dirablue** [comment]
hi @g123k 
thanks! it works.
